### ISSUE TITLE
Script - Maven dependency - version change

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#306]
Many problems linked to : 
- dependency uninstall
- version upgrade
- dependency unicity mgmt

I defined a maven dependency in many scripts of a module. This dependency contains classes specific to the module, so dependency versions will often change with the module version.

When i install the module on a new environment, no problem.
If i uninstall the module, all the scripts are removed, but the dependency is not removed from table maven_dependency.
after uninstall, i can't install a new version of the module with a different version of the dependency  (need to remove it from maven_dependency first)

Regarding dependency unicity mgmt, there's a problem with table maven_dependency : the UK is on group + artifact. But in fact there's a FK on column coordinates from adm_script_maven_dependency. So : coordinates have to be unique

Then i have a question regarding the dependency version change : is it applied (hot replacement of the classloader) ?. If not, can we add a feature to manage this (in a first time, restarting meveo is ok)

**Comment by sophieperrineau** [comment]
I Tony - i checked your code.
there's a format issue :
- all the code has been changed to be viewable with less columns (=> could you change your conf / avoid to fully reformat)
- indentation doesn't exists anymore => it's difficult to read the code

in MavenDependencyService, findScriptRelatedDependencies is ambiguous : we have to read the code to understand which dependencies are returned add javadoc and/or rename to findUniquelyReferencedFromScript. 

Then, i think that the code you've written for removal won't be ok : AfterTransaction the method "findScriptRelatedDependencies" should return nothing.

Is it possible to change the onScriptUpdated and onScriptDeleted in order to list orphans and remove them with a method that will trigger observers (not a direct sql delete, as in current removeOrphans method). And add an observer on MavenDependency in order to remove the dropped dependency from the classloader ?

**Comment by tonysviews** [comment]
@sophieperrineau - thanks for the feedback, my responses below:
- I am using Eclipse and the included Standard Java Formatter:
![image](https://user-images.githubusercontent.com/6660853/110260747-6d6e0880-7fe8-11eb-89d3-1bfb23bb804c.png)

If we should be using a different/custom formatter on eclipse, please let me know where I may find the formatter configuration file.

- I will rename and add a more detailed javadoc as requested.
- The code works because the same script instance is being used before and after the script instance is deleted.  By forcing the entity to load the maven dependencies before the script instance is deleted, the entity retains the list that can later on be reloaded in the after transaction method.  It does work but is a bit kludgy indeed.  For now, PersistenceService#remove is responsible for triggering the events and does not have a way to directly pass in optional parameters before and after the entity is removed.  Perhaps we can add a feature that allows the before transaction observer to return a generic value and pass that value to the after transaction observer.  But I believe that would be best done on a different ticket since it will entail a wider test to be done since it is dealing with a base service that is used by multiple services.
- I will look into this alternate implementation if it is possible.

**Comment by sophieperrineau** [comment]
reviewed code
tested some install
